Update multi-replace.yaml

diff --git a/.github/workflows/multi-replace.yaml b/.github/workflows/multi-replace.yaml
--- a/.github/workflows/multi-replace.yaml
+++ b/.github/workflows/multi-replace.yaml
@@ -1,15 +1,15 @@
-name: Multi Search and Replace v.3
+name: Multi Search & Replace v.4
 on:
   workflow_dispatch:
     inputs:
       search_phrases:
-        description: 'Pipe-separated list of phrases to search for'
+        description: '| separated phrases to search for'
         required: true
       replace_phrases:
-        description: 'Pipe-separated list of phrases to replace with'
+        description: '| separated phrases to replace with'
         required: true
       file_name_contains:
-        description: 'Phrase contained in the file name (optional)'
+        description: '| separated phrases in file names (optional)'
         required: false
         default: ''
 
@@ -21,35 +21,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-
       - uses: actions/setup-python@v2
         with:
           python-version: '3.x'
-
       - name: Search & Replace and Commit Changes
         env:
           SEARCH_PHRASES: ${{ github.event.inputs.search_phrases }}
           REPLACE_PHRASES: ${{ github.event.inputs.replace_phrases }}
           FILE_NAME_CONTAINS: ${{ github.event.inputs.file_name_contains }}
         run: |
-          IFS='|' read -r -a SEARCH_ARRAY <<< "${SEARCH_PHRASES}"
-          IFS='|' read -r -a REPLACE_ARRAY <<< "${REPLACE_PHRASES}"
-
-          if [ "${#SEARCH_ARRAY[@]}" -ne "${#REPLACE_ARRAY[@]}" ]; then
-            echo "Error: Mismatch in number of search & replace phrases."
-            exit 1
-          fi
-
-          for i in "${!SEARCH_ARRAY[@]}"; do
-            find . -name "*${FILE_NAME_CONTAINS}*.html" -type f \
-              -exec sed -i "s|$(printf '%s\n' "${SEARCH_ARRAY[$i]}" | sed 's:[\\/&]:\\&:g')|$(printf '%s\n' "${REPLACE_ARRAY[$i]}" | sed 's:[\\/&]:\\&:g')|g" {} +
-          done
-
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add .
-          git commit -m "Batch replace on $(date +'%Y-%m-%d')"
-
+          IFS='|' read -r -a SEARCH <<< "${SEARCH_PHRASES}"; IFS='|' read -r -a REPLACE <<< "${REPLACE_PHRASES}"; IFS='|' read -r -a FILES <<< "${FILE_NAME_CONTAINS}"
+          if [ "${#SEARCH[@]}" -ne "${#REPLACE[@]}" ]; then echo "Error: Mismatch in phrases."; exit 1; fi
+          for file in "${FILES[@]}"; do for i in "${!SEARCH[@]}"; do find . -name "*${file}*.html" -type f -exec sed -i "s|$(printf '%s' "${SEARCH[$i]}" | sed 's:[\\/&]:\\&:g')|$(printf '%s' "${REPLACE[$i]}" | sed 's:[\\/&]:\\&:g')|g" {} +; done; done
+          git config --global user.name 'github-actions[bot]'; git config --global user.email 'github-actions[bot]@users.noreply.github.com'; git add .
+          MESSAGE="Replacements on $(date +'%Y-%m-%d'):\n"; for i in "${!SEARCH[@]}"; do MESSAGE+="- '${SEARCH[$i]}' -> '${REPLACE[$i]}'\n"; done
+          git commit -m "${MESSAGE}"
       - name: Push changes
         env:
           GH_PAT: ${{ secrets.GH_PAT }}
